//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_OES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stu_id { get; set; }
        public string stu_name { get; set; }
        public string mobile { get; set; }
        public string city { get; set; }
        public string State { get; set; }
        public System.DateTime DOB { get; set; }
        public string Qualification { get; set; }
        public string Completion { get; set; }
    }
}
